TaskLancer/Models/SkillTag.cs
using System.ComponentModel.DataAnnotations;
using TaskLancer.Areas.Identity.Data;

namespace TaskLancer.Models
{
    public class SkillTag
    {
        [Key]
        public int SkillTagId { get; set; }

        public string Name { get; set; }

        public string? Description { get; set; }

        public virtual ICollection<TaskLancerUser>? TaskLancerUsers { get; set; }

        public virtual ICollection<Project.DAL.Task>? Tasks { get; set; }
    }
}

TaskLancer/Controllers/BackOfficeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Web.Http;
using TaskLancer.Areas.Identity.Data;
using TaskLancer.Data;
using TaskLancer.Models.BackOffice.BLL;
using TaskLancer.Models.Contracting.DAL;
using TaskLancer.Services;
using HttpPostAttribute = Microsoft.AspNetCore.Mvc.HttpPostAttribute;

namespace TaskLancer.Controllers
{
    public class BackOfficeController : Controller
    {
        private readonly TaskLancerContext _context;
        private readonly IBackOfficeService _backofficeService;
        private readonly UserManager<TaskLancerUser> _userManager;
        private readonly IStatisticsService _statisticsService;

        public BackOfficeController(TaskLancerContext context, IBackOfficeService backofficeService, UserManager<TaskLancerUser> userManager, IStatisticsService statisticsService)
        {
            _context = context;
            _backofficeService = backofficeService;
            _userManager = userManager;
            _statisticsService = statisticsService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ManageUsers()
        {
            List<InputModel> model = new List<InputModel>();
            List<TaskLancerUser> users = _context.Users.ToList();
            foreach (var user in users)
            {
                InputModel input = new InputModel
                {
                    Id = user.Id,
                    UserName = user.UserName,
                    UserRole = _backofficeService.getUserRole(user.Id, _userManager),
                };
                model.Add(input);
            }
            return View(model);
        }

        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            TaskLancerUser user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            InputModel input = new InputModel
            {
                Id = user.Id,
                UserName = user.UserName,
                UserRole = _backofficeService.getUserRole(user.Id, _userManager),
            };
            ViewBag.Message = "";
            return View(input);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Edit(string id, InputModel input)
        {
            if (id != input.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _backofficeService.ChangeUserRole(input.Id, input.UserRole, _userManager);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(input.UserRole))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ManageUsers));
            }
            return View(input);
        }

        public async Task<IActionResult> Statistics()
        {
            System.Security.Claims.ClaimsPrincipal currentUser = this.User;

            TaskLancerUser user = await _userManager.GetUserAsync(currentUser);
            List<int> avg = await _statisticsService.AverageTimeContractsCompleted();
            StatisticsModel model = new StatisticsModel
            {
                totalUsers = await _statisticsService.UserTotal(),
                totalManagers = await _statisticsService.ParticipatingManagerTotal(),
                totalFreelancers = await _statisticsService.ParticipatingFreelancerTotal(),
                totalProjects = await _statisticsService.ProjectsTotal(),
                totalContracts = await _statisticsService.ContractingProcessesTotal(null),
                totalContractsPublished = await _statisticsService.ContractingProcessesTotal(ContractingProcessState.Published),
                totalContractsPendingPayment = await _statisticsService.ContractingProcessesTotal(ContractingProcessState.Pending_Payment),
                totalContractsOngoing = await _statisticsService.ContractingProcessesTotal(ContractingProcessState.Ordered),
                totalContractsUnderEvaluation = await _statisticsService.ContractingProcessesTotal(ContractingProcessState.Under_Evaluation),
                totalContractsCompleted = await _statisticsService.ContractingProcessesTotal(ContractingProcessState.Completed),
                totalContractsCanceled = await _statisticsService.ContractingProcessesTotal(ContractingProcessState.Canceled),
                totalTransactions = await _statisticsService.PaymentTotal(),
                platformProfit = await _statisticsService.PlatformProfitFinancialTotal(),
                averageTimeContractsCompleted = "" + avg.ElementAt(0) + "d" + avg.ElementAt(1) + "h" + avg.ElementAt(2) + "m",
            };

            return View(model);
        }
        private bool RoleExists(string name)
        {
            return _context.Roles.Any(e => e.Name == name);
        }

        public class InputModel
        {
            [Display(Name = "Id")]
            public string Id { get; set; }

            [Display(Name = "UserName")]
            public string UserName { get; set; }

            [Display(Name = "UserRole")]
            public string UserRole { get; set; }

        }

        public class StatisticsModel
        {
            public int totalUsers { get; set; }

            public int totalManagers { get; set; }

            public int totalFreelancers { get; set; }

            public int totalManagersAndFreelancers { get; set; }

            public int totalProjects { get; set; }

            public int totalContracts { get; set; }

            public int totalContractsPublished { get; set; }

            public int totalContractsPendingPayment { get; set; }

            public int totalContractsOngoing { get; set; }

            public int totalContractsUnderEvaluation { get; set; }

            public int totalContractsCompleted { get; set; }

            public int totalContractsCanceled { get; set; }

            public int totalTransactions { get; set; }

            public float platformProfit { get; set; }
            public String averageTimeContractsCompleted { get; set; }
        }
    }
}

TaskLancer/Controllers/CategoryTagsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TaskLancer.Data;
using TaskLancer.Models.Project.DAL;
using TaskLancer.Services;

namespace TaskLancer.Controllers
{
    public class CategoryTagsController : Controller
    {
        private readonly TaskLancerContext _context;
        private readonly ICategoryTagService _categorytagservice;
        public CategoryTagsController(TaskLancerContext context, ICategoryTagService categorytagservice)
        {
            _context = context;
            _categorytagservice = categorytagservice;
        }

        // GET: CategoryTags
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.CategoryTag.ToListAsync());
        }

        // GET: CategoryTags/Details/5
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoryTag = await _context.CategoryTag
                .FirstOrDefaultAsync(m => m.CategoryTagId == id);
            if (categoryTag == null)
            {
                return NotFound();
            }

            return View(categoryTag);
        }

        // GET: CategoryTags/Create
        [Authorize(Roles = "administrator")]
        public IActionResult Create()
        {
            ViewBag.Message = "";
            return View();
        }

        // POST: CategoryTags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Create([Bind("CategoryTagId,Name,Description")] CategoryTag categoryTag)
        {
            if (ModelState.IsValid)
            {
                //chamar serviço
                if (!_categorytagservice.CheckIfExists(categoryTag))
                {
                    await _categorytagservice.AddCategoryTag(categoryTag.Name, categoryTag.Description);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.Message = "CategoryTag already exist";
                    return View(categoryTag);
                }
            }
            return View(categoryTag);
        }

        // GET: CategoryTags/Edit/5
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoryTag = await _context.CategoryTag.FindAsync(id);
            if (categoryTag == null)
            {
                return NotFound();
            }
            ViewBag.Message = "";
            return View(categoryTag);
        }

        // POST: CategoryTags/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryTagId,Name,Description")] CategoryTag categoryTag)
        {
            if (id != categoryTag.CategoryTagId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //chamar serviço
                    CategoryTag oldtag = _context.CategoryTag.Where<CategoryTag>(e => e.CategoryTagId == id).FirstOrDefault();
                    if (oldtag.Name.Equals(categoryTag.Name))
                    {
                        await _categorytagservice.ChangeCategoryTag(categoryTag.CategoryTagId, categoryTag.Name, categoryTag.Description);
                    }
                    else
                    {
                        if (!_categorytagservice.CheckIfExists(categoryTag))
                        {
                            await _categorytagservice.ChangeCategoryTag(categoryTag.CategoryTagId, categoryTag.Name, categoryTag.Description);
                        }
                        else
                        {
                            ViewBag.Message = "CategoryTag already exist";
                            return View(categoryTag);
                        }
                    }
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryTagExists(categoryTag.CategoryTagId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(categoryTag);
        }

        // GET: CategoryTags/Delete/5
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var categoryTag = await _context.CategoryTag
                .FirstOrDefaultAsync(m => m.CategoryTagId == id);
            if (categoryTag == null)
            {
                return NotFound();
            }

            return View(categoryTag);
        }

        // POST: CategoryTags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //chamar serviço
            await _categorytagservice.DeleteCategoryTag(id);
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "administrator")]
        private bool CategoryTagExists(int id)
        {
            return _context.CategoryTag.Any(e => e.CategoryTagId == id);
        }
    }
}

TaskLancer/Views/SkillTags/Create.cshtml
@model TaskLancer.Models.SkillTag

@{
    ViewData["Title"] = "Create SkillTag";
}

<h4 class="pt-3">Create SkillTag</h4>
<hr />
<div class="card">
    <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="BackOffice" asp-action="Index">Manage Content</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="ManageUsers">Manage Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="Statistics">Statistics</a>
                </li>
            </ul>
        </div>
    <div class="card-body">
        @if(!String.IsNullOrEmpty(ViewBag.Message))
        {
            <div class="alert alert-danger" role="alert">
                @ViewBag.Message
            </div>
        }

        <div class="row">
            <div class="col-md-4">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <p></p>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn button-colors" />
                    </div>
                </form>
            </div>
        </div>
        <p></p>
        <div>
            <a asp-action="Index" class="btn button-colors">Back to List</a>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskLancer/Views/SkillTags/Delete.cshtml
@model TaskLancer.Models.SkillTag

@{
    ViewData["Title"] = "Delete SkillTag";
}

<h4 class="pt-3">Delete SkillTag</h4>
<hr />
<div class="card">
    <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="BackOffice" asp-action="Index">Manage Content</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="ManageUsers">Manage Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="Statistics">Statistics</a>
                </li>
            </ul>
        </div>
    <div class="card-body">
        <h4 class="pt-3">Are you sure you want to delete this Tag?</h4>
        <div>
            <h4>SkillTag</h4>
            <hr />
            <dl class="row">
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </dl>
    
            <form asp-action="Delete">
                <input type="hidden" asp-for="SkillTagId" />
                <input type="submit" value="Delete" class="btn btn-outline-danger" /> |
                <a asp-action="Index" class="btn button-colors">Back to List</a>
            </form>
        </div>
    </div>
</div>

TaskLancer/Views/SkillTags/Details.cshtml
@model TaskLancer.Models.SkillTag

@{
    ViewData["Title"] = "Details SkillTag";
}

<h4 class="pt-3">Details SkillTag</h4>
<hr />
<div class="card">
    <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="BackOffice" asp-action="Index">Manage Content</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="ManageUsers">Manage Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="Statistics">Statistics</a>
                </li>
            </ul>
        </div>
    <div class="card-body">
        <div>
            <h4>SkillTag</h4>
            <hr />
            <dl class="row">
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Name)
                </dd>
                <dt class = "col-sm-2">
                    @Html.DisplayNameFor(model => model.Description)
                </dt>
                <dd class = "col-sm-10">
                    @Html.DisplayFor(model => model.Description)
                </dd>
            </dl>
        </div>
        <div>
            <a asp-action="Index" class="btn button-colors">Back to List</a>
        </div>
    </div>
</div>

TaskLancer/Views/SkillTags/Edit.cshtml
@model TaskLancer.Models.SkillTag

@{
    ViewData["Title"] = "Edit SkillTag";
}

<h4 class="pt-3">Edit SkillTag</h4>
<hr />
<div class="card">
    <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="BackOffice" asp-action="Index">Manage Content</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="ManageUsers">Manage Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="Statistics">Statistics</a>
                </li>
            </ul>
        </div>
    <div class="card-body">
        @if(!String.IsNullOrEmpty(ViewBag.Message))
        {
            <div class="alert alert-danger" role="alert">
                @ViewBag.Message
            </div>
        }

        <div class="row">
            <div class="col-md-4">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="SkillTagId" />
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <p></p>
                    <div class="form-group">
                        <input type="submit" value="Save" class="btn button-colors" />
                    </div>
                </form>
            </div>
        </div>
        <p></p>
        <div>
            <a asp-action="Index" class="btn button-colors">Back to List</a>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskLancer/Views/SkillTags/Index.cshtml
@model IEnumerable<TaskLancer.Models.SkillTag>

@{
    ViewData["Title"] = "BackOffice - Manage SkillTags";
}

<h4 class="pt-3">BackOffice - Manage SkillTags</h4>
<hr />
<div class="card">
    <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link active" asp-controller="BackOffice" asp-action="Index">Manage Content</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="ManageUsers">Manage Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="Statistics">Statistics</a>
                </li>
            </ul>
        </div>
    <div class="card-body">
        <p>
            <a asp-controller="CategoryTags" asp-action="Index" class="btn button-colors"> Manage CategoryTags</a>
        </p>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Description)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
             @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.SkillTagId" class="btn button-colors">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.SkillTagId" class="btn button-colors">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.SkillTagId" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>
             }
            </tbody>
        </table>
        <a asp-action="Create" class="btn button-colors">New SkillTag</a>
    </div>
</div>