TaskLancer/Models/Project/BLL/BoardDTO.cs
namespace TaskLancer.Models.Project.BLL
{
    public class BoardDTO
    {
        public int? BoardId { get; set; }
        public ICollection<ColumnDTO>? Columns { get; set; }
    }
}

TaskLancer/Models/Project/BLL/ColumnDTO.cs
namespace TaskLancer.Models.Project.BLL
{
    public class ColumnDTO
    {
        public int? ColumnId { get; set; }
        public string? Name { get; set; }
        public string? Color { get; set; }
        public List<TaskDTO>? Tasks { get; set; }
    }
}

TaskLancer/Models/Project/BLL/IProjectService.cs
using TaskLancer.Models.Project.DAL;


namespace TaskLancer.Models.Project.BLL
{
    public interface IProjectService
    {
        Task<int> CreateProjectAsync(string name, string description, bool isPublic, ICollection<CategoryTag> categoryTags, string authenticatedUserId);
        Task<int> CreateUserProject(string userId);
        Task<DAL.Project> GetProjectDetailsAsync(int projectId, string authenticatedUserId);

        Task<List<DAL.Project>> GetAllUserProjects(string userId);

        Task<int> SetProjectDetailsAsync(int projectId, string name, string description, bool isPublic, ICollection<CategoryTag> categoryTags, string authenticatedUserId);

        Task<DAL.Project> GetProject(int boardId);

        Task<Board> GetBoard(int boardId);

        Task<int> RemoveBoard(int boardId);

        Task<Column> CreateColumn(int boardId, Column column);

        Task<Column> EditColumn(int boardId, Column column);

        Task<int> RemoveColumn(int boardId, int columnId);

        Task<int> MoveColumn(int boardId, int columnId, int newPosition);

        Task<DAL.Task> CreateTask(int boardId, int columnId, DAL.Task task);

        Task<DAL.Task> GetTask(int taskId);

        Task<int> EditTask(int boardId, DAL.Task task);

        Task<int> MoveTask(int boardId, int taskId, int fromColumnId, int toColumnId, int newPosition);

        Task<int> RemoveTask(int boardId, int columnId, int taskId);

        string generateJwt(string userId, int boardId);

        bool validateJWT(string token, int boardId);

        Task<int> GetProjectBoardId(int projectId);

    }
}

TaskLancer/Models/Project/BLL/TaskDTO.cs
namespace TaskLancer.Models.Project.BLL
{
    public class TaskDTO
    {
        public int? TaskId { get; set; }
        public string? Title { get; set; }
        public string? Description { get; set; }
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public ICollection<SkillTagDTO>? SkillTags { get; set; }
        public bool? HasContractingProcess { get; set; }
    }
}

TaskLancer/Models/Project/DAL/Board.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TaskLancer.Models.Project.DAL
{
    public class Board
    {
        [Key]
        public int BoardId { get; set; }
        public ICollection<Column>? Columns { get; set; }
        public string ColumnsOrder { get; set; }
        [ForeignKey("Project")]
        public int ProjectId { get; set; }
        public Project? Project { get; set; }

    }
}

TaskLancer/Areas/Identity/Pages/Account/AccessDenied.cshtml.cs
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
#nullable disable

using Microsoft.AspNetCore.Mvc.RazorPages;

namespace TaskLancer.Areas.Identity.Pages.Account
{
    /// <summary>
    ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
    ///     directly from your code. This API may change or be removed in future releases.
    /// </summary>
    public class AccessDeniedModel : PageModel
    {
        /// <summary>
        ///     This API supports the ASP.NET Core Identity default UI infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public void OnGet()
        {
        }
    }
}

TaskLancer/Controllers/ProfileController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TaskLancer.Areas.Identity.Data;
using TaskLancer.Data;
using TaskLancer.Models;
using TaskLancer.Models.Project;

using TaskLancer.Services;

namespace TaskLancer.Controllers
{
    public class ProfileController : Controller
    {
        private readonly TaskLancerContext _context;
        private readonly UserManager<TaskLancerUser> _userManager;
        private readonly IProfileService _profileService;

        public ProfileController(TaskLancerContext context, UserManager<TaskLancerUser> userManager, IProfileService profileService)
        {
            _context = context;
            _userManager = userManager;
            _profileService = profileService;
        }


        [Authorize]
        public async Task<IActionResult> DetailsUserProfile()
        {
            System.Security.Claims.ClaimsPrincipal currentUser = this.User;
            TaskLancerUser user = await _userManager.GetUserAsync(currentUser);

            if(user != null)
            {
                return RedirectToAction("Details", new { username = user.UserName });
            }

            return NotFound();
        }

        [Authorize]
        // GET: Projects/Details/5
        public async Task<IActionResult> Details(string? username)
        {

            if (username == null)
            {
                return NotFound();
            }

            //var project = await _context.Project
            //    .FirstOrDefaultAsync(m => m.ProjectId == id);

            System.Security.Claims.ClaimsPrincipal currentUser = this.User;

            TaskLancerUser user;

            try{
                user = await _profileService.GetUserWithSkillTagsAsync(username);
            } catch (ArgumentException e)
            {
                Console.WriteLine(e.Message);
                return NotFound();
            }

            ViewBag.hasEdit = User.Identity.Name == user.UserName;

            List<SkillTag> allSkillTags = await _context.SkillTag.ToListAsync();

            IEnumerable<SelectListItem> SkillTagsSelectList = new SelectList(allSkillTags, "SkillTagId", "Name");

            ViewBag.SkillTagsSelectList = SkillTagsSelectList;

            var selectedValues = new List<int>();

            if (user.SkillTags != null)
            {
                foreach (var tag in user.SkillTags)
                {
                    selectedValues.Add(tag.SkillTagId);
                }
            }

            InputModel input = new InputModel
            {
                UserName = user.UserName,
                FullName = user.FirstName + " " + user.LastName,
                Biography = user.Biography,
                Curriculum = user.Curriculum,
                SelectedSkillTags = selectedValues,
                
            };


            return View(input);
        }

        public class InputModel
        {
            public string UserName { get; set; }

            [Display(Name = "Full Name")]
            public string FullName { get; set; }

            [Display(Name = "Biography")]
            public string Biography { get; set; }

            [Display(Name = "Curriculum")]
            public string Curriculum { get; set; }

            [Display(Name = "Skill Tags")]
            public IEnumerable<int> SelectedSkillTags { get; set; }

        }
    }
}

TaskLancer/Controllers/ProjectsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Hosting.Server.Features;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TaskLancer.Areas.Identity.Data;
using TaskLancer.Data;
using TaskLancer.Models.Project.BLL;
using TaskLancer.Models.Project.DAL;

namespace TaskLancer.Controllers
{
    public class ProjectsController : Controller
    {
        private readonly TaskLancerContext _context;
        private readonly UserManager<TaskLancerUser> _userManager;
        private readonly IProjectService _projectService;
        private readonly IServer _server;

        public ProjectsController(TaskLancerContext context, UserManager<TaskLancerUser> userManager, IProjectService projectService, IServer server )
        {
            _context = context;
            _userManager = userManager;
            _projectService = projectService;
            _server = server;
        }

        [Authorize]
        public  IActionResult AccessDenied()
        {
            return View();
        }

        //[Authorize(Roles = "administrator")]
        //// GET: Projects
        //public async Task<IActionResult> Index()
        //{
        //    return View(await _context.Project.ToListAsync());
        //}

        [Authorize]
        public async Task<IActionResult> DetailsUserProject()
        {
            System.Security.Claims.ClaimsPrincipal currentUser = this.User;
            TaskLancerUser user = await _userManager.GetUserAsync(currentUser);

            if(user != null)
            {
                var project = await _context.Project.Where(x => x.Manager == user).FirstOrDefaultAsync();
                if(project != null)
                {
                    return RedirectToAction("Details", new { id = project.ProjectId });
                }
            }

            return NotFound();
        }

        [Authorize]
        public async Task<IActionResult> Board(int id)
        {
            System.Security.Claims.ClaimsPrincipal currentUser = this.User;
            TaskLancerUser user = await _userManager.GetUserAsync(currentUser);

            Project project = await _context.Project.Include(p => p.Manager).Include(p => p.Board).FirstOrDefaultAsync(p => p.Board.BoardId == id);

            if(project == null)
            {
                return RedirectToAction("AccessDenied");
            }

            if(!project.IsPublic && project.Manager != user)
            {
                return RedirectToAction("AccessDenied");
            }

            string token = "";

            if (project.Manager == user)
            {
                token = _projectService.generateJwt(user.Id, id);
            }

            ViewBag.Host = _server.Features.Get<IServerAddressesFeature>().Addresses.First();
            ViewBag.ProjectName = project.Name;
            ViewBag.ProjectId = project.ProjectId;
            ViewBag.BoardId = id;
            ViewBag.Token = token;
            return View();
        }

        [Authorize]
        // GET: Projects/Details/5
        public async Task<IActionResult> Details(int? id, string? statusMessage="")
        {

            if (id == null)
            {
                return NotFound();
            }

            //var project = await _context.Project
            //    .FirstOrDefaultAsync(m => m.ProjectId == id);

            System.Security.Claims.ClaimsPrincipal currentUser = this.User;
            TaskLancerUser user = await _userManager.GetUserAsync(currentUser);

            Project project;

            try{
                project = await _projectService.GetProjectDetailsAsync((int)id, user.Id);
            } catch (ArgumentException e)
            {
                Console.WriteLine(e.Message);
                return RedirectToAction("AccessDenied");
            }

            ViewBag.BoardId = await _projectService.GetProjectBoardId(project.ProjectId);

            ViewBag.hasEdit = project.Manager.Id == user.Id;
            ViewBag.managerUserName = project.Manager.UserName;

            // Obter todas as tags
            List<CategoryTag> allCategoryTags = await _context.CategoryTag.ToListAsync();
            // criar uma select list que consiste em todas as tags, o atributo que serve de id e o que serve de display
            IEnumerable<SelectListItem> CategoryTagsSelectList = new SelectList(allCategoryTags, "CategoryTagId", "Name");
            // adicionar à view bag
            ViewBag.CategoryTagsSelectList = CategoryTagsSelectList;

            // determinar as tags que ja estão selecionadas
            var selectedValues = new List<int>();
            if (project.CategoryTags != null)
            {
                foreach (var tag in project.CategoryTags)
                {
                    selectedValues.Add(tag.CategoryTagId);
                }
            }

            // construir um input model com a lista de ids de tags em vez de tags
            InputModel input = new InputModel
            {
                ProjectId = project.ProjectId,
                Name = project.Name,
                Description = project.Description,
                IsPublic = project.IsPublic,
                Manager = project.Manager,
                SelectedCategoryTags = selectedValues,
                StatusMessage = statusMessage
            };


            return View(input);
        }

        public class InputModel
        {
            public int ProjectId { get; set; }
            [Required]
            [MinLength(3)]
            [Display(Name = "Project Name")]
            public string Name { get; set; }
            public string? Description { get; set; }

            [Display(Name = "Is Public")]
            public bool IsPublic { get; set; }
            public TaskLancerUser? Manager { get; set; }

            [Display(Name = "Category Tags")]
            public IEnumerable<int> SelectedCategoryTags { get; set; }

            public string? StatusMessage { get; set; }
        }


        // GET: Projects/Create
        //[Authorize(Roles = "administrator")]
        public async Task<IActionResult> Create(string? statusMessage = "")
        {
            List<CategoryTag> allCategoryTags = await _context.CategoryTag.ToListAsync();

            IEnumerable<SelectListItem> CategoryTagsSelectList = new SelectList(allCategoryTags, "CategoryTagId", "Name");

            ViewBag.CategoryTagsSelectList = CategoryTagsSelectList;

            var selectedValues = new List<int>();

            InputModel input = new InputModel
            {
                Name = "",
                Description = "",
                IsPublic = true,
                SelectedCategoryTags = selectedValues,
                StatusMessage = statusMessage
            };


            return View(input);
        }

        // POST: Projects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(InputModel input)
        {
            if (ModelState.IsValid)
            {
                List<CategoryTag> allCategoryTags = await _context.CategoryTag.ToListAsync();
                ICollection<CategoryTag> categoryTags = new List<CategoryTag>();

                if (input.SelectedCategoryTags != null)
                {
                    foreach (int selectedId in input.SelectedCategoryTags)
                    {
                        CategoryTag categoryTag = allCategoryTags.Where(x => x.CategoryTagId == selectedId).FirstOrDefault();
                        if (categoryTag != null)
                        {
                            categoryTags.Add(categoryTag);
                        }
                    }
                }

                try
                {
                    System.Security.Claims.ClaimsPrincipal currentUser = this.User;
                    TaskLancerUser user = await _userManager.GetUserAsync(currentUser);

                    int projectId = await _projectService.CreateProjectAsync(input.Name,
                        input.Description, input.IsPublic, categoryTags, user.Id);

                    return RedirectToAction(nameof(Details), new { id = projectId, statusMessage = "New project created successfully!" });
                }
                catch (ArgumentException e)
                {
                    Console.WriteLine(e.Message);
                    return RedirectToAction("AccessDenied");
                }                
            }
            return View(input);
        }

        // GET: Projects/Edit/5
        [Authorize]

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            System.Security.Claims.ClaimsPrincipal currentUser = this.User;
            TaskLancerUser user = await _userManager.GetUserAsync(currentUser);

            Project project;

            try
            {
                project = await _projectService.GetProjectDetailsAsync((int)id, user.Id);
            }
            catch (ArgumentException e)
            {
                Console.WriteLine(e.Message);
                return RedirectToAction("AccessDenied");
            }

            if(project.Manager.Id != user.Id)
            {
                return RedirectToAction("AccessDenied");
            }

            List<CategoryTag> allCategoryTags = await _context.CategoryTag.ToListAsync();

TaskLancer/Views/Projects/AccessDenied.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Access to project denied.</h1>

TaskLancer/Views/Projects/Board.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Board";
}

@section Scripts {
    <script src="~/js/TaskBoard/main.js" type="module"></script>
    <script src="~/js/TaskBoard/polyfills.js" type="module"></script>
    <script src="~/js/TaskBoard/runtime.js" type="module"></script>
}

<div>
    <h4 class="pt-3">@ViewBag.ProjectName</h4>
    <hr />
</div>


<div class="card flex-fill">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link tasklancer-color" asp-controller="Projects" asp-action="Details" asp-route-id="@ViewBag.ProjectId">Details</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" asp-controller="Projects" asp-action="Board" asp-route-id="@ViewBag.BoardId">Board</a>
            </li>
        </ul>
    </div>
    <div class="card-body overflow-auto" style="height: 25em"> 
        <taskboard-element token="@ViewBag.Token" board-id="@ViewBag.BoardId" host="@ViewBag.Host"></taskboard-element>
    </div>
            
    </div>


    <link href="~/js/TaskBoard/styles.css" rel="stylesheet" />

TaskLancer/Views/Projects/Create.cshtml
@model TaskLancer.Controllers.ProjectsController.InputModel

@{
    ViewData["Title"] = "Edit";
}

<style>
    input[type="checkbox"]:disabled {
    background-color: #008085;
    border-color: #008085;
}

input[type="checkbox"]:enabled {
    background-color: #008085;
    border-color: #008085;
}

input[type="checkbox"] {
    background-color: white;
    border-color: #008085;
}
</style>

<h4 class="pt-3">New Project</h4>
<partial name="_StatusMessage" for="StatusMessage" />
<hr />
<div class="row">
    <div class="col">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group py-3 col-md-4">
                <div class="d-flex">
                    <label asp-for="Name" class="control-label"></label>
                    <div class="ps-2">
                            <i class="fa fa-info-circle tasklancer-color align-self-center" aria-hidden="true"  data-bs-toggle="tooltip"  data-bs-placement="right" title="A name that fits your project."></i>
                    </div>
                </div>

                 <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group pb-3">
                <div class="d-flex">
                    <label asp-for="Description" class="control-label"></label>
                    <div class="ps-2">
                            <i class="fa fa-info-circle tasklancer-color align-self-center" aria-hidden="true"  data-bs-toggle="tooltip"  data-bs-placement="right" title="A description for your audience and stakeholders."></i>
                    </div>
                </div>
                <input asp-for="Description" id="Model_Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-floating mb-4 pb-3">
                <select multiple asp-for="SelectedCategoryTags" asp-items="ViewBag.CategoryTagsSelectList" class="form-control" style="width: 100%" id="tag-selector"></select>
                                <label asp-for="SelectedCategoryTags" class="form-label"></label>

            </div>
            <div class="form-group form-check form-switch pb-3">
                <label class="form-check-label">
                    <input class="form-check-input" type="checkbox" id="flexSwitch" asp-for="IsPublic" /> @Html.DisplayNameFor(model => model.IsPublic)
                </label>
            </div>
            <div class="d-flex justify-content-end pb-3">
                <div class="form-group col-sm-2 px-3">
                   <input type="button" disabled value="Cancel" class="btn btn-outline-danger w-100" />
                </div>
                <div class="form-group col-sm-2 px-3">
                    <input type="submit" value="Create" class="btn btn-primary button-colors w-100" />
                </div>
            </div>
            
        </form>
    </div>
</div>

<link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
<link href="~/lib/select2-bootstrap-5-theme/select2-bootstrap-5-theme.min.css" rel="stylesheet" />
<link href="~/lib/rich-text/richtext.min.css" rel="stylesheet" />
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/lib/select2/js/select2.full.min.js"></script>
    <script src="~/lib/rich-text/jquery.richtext.min.js"></script>
    <script type="text/javascript">
        var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
        var tooltipList = tooltipTriggerList.map(function (tooltipTriggerEl) {
          return new bootstrap.Tooltip(tooltipTriggerEl)
        })

        $("#Model_Description").richText({
              fonts: false,
              fontColor: false,
              fontSize: false,
              removeStyles: false,
              code: false,
              class: "form-control",

              useSingleQuotes: true,
        });
       $("#Model_Description").trigger("change");
       //$("#Input_Curriculum").richText({
       //       useSingleQuotes: true,
       // });
       //$("#Input_Curriculum").trigger("change");
        $("#tag-selector").select2({
            placeholder: "Select project categories",
            allowClear: true,
            theme: "bootstrap-5",
            dropdownParent: $("#tag-selector").parent(), // Required for dropdown styling
        });
    </script>
}

TaskLancer/Views/Projects/Details.cshtml
@model TaskLancer.Controllers.ProjectsController.InputModel

@{
    ViewData["Title"] = "Details";
}

<style>
    input[type="checkbox"]:disabled {
        background-color: #008085;
        border-color: #008085;
    }

    input[type="checkbox"]:enabled {
        background-color: #008085;
        border-color: #008085;
    }

    input[type="checkbox"] {
        background-color: white;
        border-color: #008085;
    }
</style>

<div>
    <h4 class="pt-3">@Html.DisplayFor(model => model.Name)</h4>
    <hr />


    <div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page"  asp-controller="Projects" asp-action="DetailsUserProject">Details</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link tasklancer-color" asp-controller="Projects" asp-action="Board" asp-route-id="@ViewBag.BoardId">Board</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
             <partial name="_StatusMessage" for="StatusMessage" />

            <dl class="row">
                <div class="d-flex col-sm-12">
                    <div class="row flex-fill">
                <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Name)
                </dt>
                <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Name)
                </dd>

        </div>

        <div class="">
                        @if (ViewBag.hasEdit)
                        {
                <a asp-action="Edit" asp-route-id="@Model?.ProjectId"><i class="fa fa-pencil-square-o fa-lg align-self-center" aria-hidden="true"></i></a>
                        }
        </div>
    </div>

    <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Description)
    </dt>
    <dd class="col-sm-10 border border-primary overflow-auto richText-display-box">
                    @*@Html.DisplayFor(model => model.Description)*@
                    @Html.Raw(Model.Description)
    </dd>
    <dt class="col-sm-2">
        Category Tags:
    </dt>
    <dd class="col-sm-10 p-0">
        <select multiple disabled asp-for="SelectedCategoryTags" asp-items="ViewBag.CategoryTagsSelectList" style="width: 100%" id="tag-selector"></select>
    </dd>
    <dt class="col-sm-2">
        Project Manager:
    </dt>
    <dd class="col-sm-10 p-0">
        <a class="nav-link p-0" asp-controller="Profile" asp-action="Details" asp-route-username="@Model.Manager.UserName">@Model.Manager.UserName</a>
    </dd>
    <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.IsPublic)
    </dt>
    <dd class="col-sm-10 form-check form-switch">
        <input class="form-check-input" type="checkbox" id="flexSwitch" checked=@Model.IsPublic disabled>
    </dd>
    </dl>


</div>






@*
<div>
    

      <taskBoard></taskBoard>

</div>*@

<link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
<link href="~/lib/select2-bootstrap-5-theme/select2-bootstrap-5-theme.min.css" rel="stylesheet" />
<link href="~/lib/rich-text/richtext.min.css" rel="stylesheet" />
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<style>
    .select2-search {
        height: 0 !important;
    }

    .select2-selection__rendered {
        padding-top: 0.25em !important;
    }

    /*#description-rich .innercontents  {
            width: 100% !important;*/
    }
</style>

@section Scripts {

   
    <script src="~/lib/select2/js/select2.full.min.js"></script>
    <script src="~/lib/rich-text/jquery.richtext.min.js"></script>
<script type="text/javascript">
    // $("#Input_Biography").richText({
    //       useSingleQuotes: true,
    // });
    //$("#Input_Biography").trigger("change");
    //$("#Input_Curriculum").richText({
    //       useSingleQuotes: true,
    // });
    //$("#Input_Curriculum").trigger("change");
     $("#tag-selector").select2({
         placeholder: "Select project categories",
         allowClear: true,
         theme: "bootstrap-5",
         dropdownParent: $("#tag-selector").parent(), // Required for dropdown styling
     });
</script>

@*<script src="~/dist/tasklancer-board/runtime.156609f8cece34a3.js" type="module"></script>
      <script  src="~/dist/tasklancer-board/polyfills.76d40db98c5441bd.js" type="module"></script>
      <script  src="~/dist/tasklancer-board/main.b8cfe79b7abf5e11.js" type="module"></script>
      <link href="~/dist/tasklancer-board/styles.4951656e934288fa.css" rel="stylesheet" />*@
}