TaskLancer/Models/BackOffice/BLL/BackOfficeService.cs
using Microsoft.AspNetCore.Identity;
using TaskLancer.Areas.Identity.Data;
using TaskLancer.Data;

namespace TaskLancer.Models.BackOffice.BLL
{
    public class BackOfficeService : IBackOfficeService
    {
        private readonly TaskLancerContext _context;

        public BackOfficeService(TaskLancerContext ctx)
        {
            _context = ctx;
        }
        /// <summary>
        /// This method return the name of the role of the user with the id received
        /// </summary>
        /// <param name="id">User Id</param>
        /// <param name="userManager">UserManager service</param>
        /// <returns>Name of the role</returns>
        public string getUserRole(string id, UserManager<TaskLancerUser> userManager)
        {
            IdentityUserRole<string> userRole = _context.UserRoles.Where(u => u.UserId == id).FirstOrDefault();

            if (userRole != null)
            {
                return _context.Roles.Where(u => u.Id == userRole.RoleId).FirstOrDefault().Name;
            }
            return "No role";

        }
        /// <summary>
        /// This method change the role of the user with de id received
        /// </summary>
        /// <param name="id">User Id</param>
        /// <param name="userRole">User Role</param>
        /// <param name="userManager">UserManager service</param>
        /// <returns>Number of entries in the data base</returns>
        public async Task<int> ChangeUserRole(string id, string userRole, UserManager<TaskLancerUser> userManager)
        {
            TaskLancerUser user = await userManager.FindByIdAsync(id);
            var roles = await userManager.GetRolesAsync(user);
            if (roles.FirstOrDefault() != null)
            {
                await userManager.RemoveFromRoleAsync(user, roles.FirstOrDefault());
            }
            if (userRole != "null")
            {
                await userManager.AddToRoleAsync(user, userRole);
            }
            return await _context.SaveChangesAsync();
        }
    }
}

TaskLancer/Models/BackOffice/BLL/IBackOfficeService.cs
using Microsoft.AspNetCore.Identity;
using TaskLancer.Areas.Identity.Data;

namespace TaskLancer.Models.BackOffice.BLL
{
    public interface IBackOfficeService
    {
        Task<int> ChangeUserRole(string id, string userRole, UserManager<TaskLancerUser> userManager);
        public string getUserRole(string id, UserManager<TaskLancerUser> userManager);
    }
}

TaskLancer/Controllers/BackOfficeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Web.Http;
using TaskLancer.Areas.Identity.Data;
using TaskLancer.Data;
using TaskLancer.Models.BackOffice.BLL;
using TaskLancer.Models.Contracting.DAL;
using TaskLancer.Services;
using HttpPostAttribute = Microsoft.AspNetCore.Mvc.HttpPostAttribute;

namespace TaskLancer.Controllers
{
    public class BackOfficeController : Controller
    {
        private readonly TaskLancerContext _context;
        private readonly IBackOfficeService _backofficeService;
        private readonly UserManager<TaskLancerUser> _userManager;
        private readonly IStatisticsService _statisticsService;

        public BackOfficeController(TaskLancerContext context, IBackOfficeService backofficeService, UserManager<TaskLancerUser> userManager, IStatisticsService statisticsService)
        {
            _context = context;
            _backofficeService = backofficeService;
            _userManager = userManager;
            _statisticsService = statisticsService;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ManageUsers()
        {
            List<InputModel> model = new List<InputModel>();
            List<TaskLancerUser> users = _context.Users.ToList();
            foreach (var user in users)
            {
                InputModel input = new InputModel
                {
                    Id = user.Id,
                    UserName = user.UserName,
                    UserRole = _backofficeService.getUserRole(user.Id, _userManager),
                };
                model.Add(input);
            }
            return View(model);
        }

        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Edit(string? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            TaskLancerUser user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            InputModel input = new InputModel
            {
                Id = user.Id,
                UserName = user.UserName,
                UserRole = _backofficeService.getUserRole(user.Id, _userManager),
            };
            ViewBag.Message = "";
            return View(input);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Edit(string id, InputModel input)
        {
            if (id != input.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _backofficeService.ChangeUserRole(input.Id, input.UserRole, _userManager);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RoleExists(input.UserRole))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(ManageUsers));
            }
            return View(input);
        }

        public async Task<IActionResult> Statistics()
        {
            System.Security.Claims.ClaimsPrincipal currentUser = this.User;

            TaskLancerUser user = await _userManager.GetUserAsync(currentUser);
            List<int> avg = await _statisticsService.AverageTimeContractsCompleted();
            StatisticsModel model = new StatisticsModel
            {
                totalUsers = await _statisticsService.UserTotal(),
                totalManagers = await _statisticsService.ParticipatingManagerTotal(),
                totalFreelancers = await _statisticsService.ParticipatingFreelancerTotal(),
                totalProjects = await _statisticsService.ProjectsTotal(),
                totalContracts = await _statisticsService.ContractingProcessesTotal(null),
                totalContractsPublished = await _statisticsService.ContractingProcessesTotal(ContractingProcessState.Published),
                totalContractsPendingPayment = await _statisticsService.ContractingProcessesTotal(ContractingProcessState.Pending_Payment),
                totalContractsOngoing = await _statisticsService.ContractingProcessesTotal(ContractingProcessState.Ordered),
                totalContractsUnderEvaluation = await _statisticsService.ContractingProcessesTotal(ContractingProcessState.Under_Evaluation),
                totalContractsCompleted = await _statisticsService.ContractingProcessesTotal(ContractingProcessState.Completed),
                totalContractsCanceled = await _statisticsService.ContractingProcessesTotal(ContractingProcessState.Canceled),
                totalTransactions = await _statisticsService.PaymentTotal(),
                platformProfit = await _statisticsService.PlatformProfitFinancialTotal(),
                averageTimeContractsCompleted = "" + avg.ElementAt(0) + "d" + avg.ElementAt(1) + "h" + avg.ElementAt(2) + "m",
            };

            return View(model);
        }
        private bool RoleExists(string name)
        {
            return _context.Roles.Any(e => e.Name == name);
        }

        public class InputModel
        {
            [Display(Name = "Id")]
            public string Id { get; set; }

            [Display(Name = "UserName")]
            public string UserName { get; set; }

            [Display(Name = "UserRole")]
            public string UserRole { get; set; }

        }

        public class StatisticsModel
        {
            public int totalUsers { get; set; }

            public int totalManagers { get; set; }

            public int totalFreelancers { get; set; }

            public int totalManagersAndFreelancers { get; set; }

            public int totalProjects { get; set; }

            public int totalContracts { get; set; }

            public int totalContractsPublished { get; set; }

            public int totalContractsPendingPayment { get; set; }

            public int totalContractsOngoing { get; set; }

            public int totalContractsUnderEvaluation { get; set; }

            public int totalContractsCompleted { get; set; }

            public int totalContractsCanceled { get; set; }

            public int totalTransactions { get; set; }

            public float platformProfit { get; set; }
            public String averageTimeContractsCompleted { get; set; }
        }
    }
}

TaskLancer/Controllers/SkillTagsController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TaskLancer.Data;
using TaskLancer.Models;
using TaskLancer.Services;

namespace TaskLancer.Controllers
{
    public class SkillTagsController : Controller
    {
        private readonly TaskLancerContext _context;
        private readonly ISkillTagService _skilltagservice;
        public SkillTagsController(TaskLancerContext context, ISkillTagService skilltagservice)
        {
            _context = context;
            _skilltagservice = skilltagservice;
        }

        // GET: SkillTags
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.SkillTag.ToListAsync());
        }

        // GET: SkillTags/Details/5
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var skillTag = await _context.SkillTag
                .FirstOrDefaultAsync(m => m.SkillTagId == id);
            if (skillTag == null)
            {
                return NotFound();
            }

            return View(skillTag);
        }

        // GET: SkillTags/Create
        [Authorize(Roles = "administrator")]
        public IActionResult Create()
        {
            ViewBag.Message = "";
            return View();
        }

        // POST: SkillTags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Create([Bind("SkillTagId,Name,Description")] SkillTag skillTag)
        {
            if (ModelState.IsValid)
            {
                    //chamar serviço
                if (!_skilltagservice.CheckIfExists(skillTag))
                {
                    await _skilltagservice.AddSkillTag(skillTag.Name, skillTag.Description);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.Message = "SkillTag Already Exists";
                    return View(skillTag);
                }
            }
            return View(skillTag);
        }

        // GET: SkillTags/Edit/5
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var skillTag = await _context.SkillTag.FindAsync(id);
            if (skillTag == null)
            {
                return NotFound();
            }
            ViewBag.Message = "";
            return View(skillTag);
        }

        // POST: SkillTags/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Edit(int id, [Bind("SkillTagId,Name,Description")] SkillTag skillTag)
        {
            if (id != skillTag.SkillTagId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    //chamar serviço
                    SkillTag oldtag = _context.SkillTag.Where<SkillTag>(e => e.SkillTagId == id).FirstOrDefault();
                    if (oldtag.Name.Equals(skillTag.Name))
                    {
                        await _skilltagservice.ChangeSkillTag(skillTag.SkillTagId, skillTag.Name, skillTag.Description);
                    }
                    else
                    {
                        if (!_skilltagservice.CheckIfExists(skillTag))
                        {
                            await _skilltagservice.ChangeSkillTag(skillTag.SkillTagId, skillTag.Name, skillTag.Description);
                        }
                        else
                        {
                            ViewBag.Message = "SkillTag Already Exists";
                            return View(skillTag);
                        }
                    }       
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SkillTagExists(skillTag.SkillTagId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(skillTag);
        }

        // GET: SkillTags/Delete/5
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var skillTag = await _context.SkillTag
                .FirstOrDefaultAsync(m => m.SkillTagId == id);
            if (skillTag == null)
            {
                return NotFound();
            }

            return View(skillTag);
        }

        // POST: SkillTags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "administrator")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //chamar serviço
            await _skilltagservice.DeleteSkillTag(id);
            return RedirectToAction(nameof(Index));
        }

        private bool SkillTagExists(int id)
        {
            return _context.SkillTag.Any(e => e.SkillTagId == id);
        }
    }
}

TaskLancer/Views/BackOffice/Edit.cshtml
@model TaskLancer.Controllers.BackOfficeController.InputModel

@{
    ViewData["Title"] = "Edit User";
}

<h4 class="pt-3">Edit User</h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly/>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" readonly/>
            </div>
            <div class="form-group">
                <label asp-for="UserRole" class="control-label"></label>
                <select asp-for="UserRole" class = "form-select">
                    @if (Model.UserRole.Equals("administrator"))
                    {
                        <option value = "administrator" selected>Administrator</option>
                        <option value = "moderator">Moderator</option>
                        <option value = "null">No Role</option>
                    }
                    else if (Model.UserRole.Equals("moderator"))
                    {
                        <option value = "moderator" selected>Moderator</option>
                        <option value = "administrator">Administrator</option>
                        <option value = "null">No Role</option>
                    }
                    else
                    {
                        <option value = "null" selected>No Role</option>
                        <option value = "moderator">Moderator</option>
                        <option value = "administrator">Administrator</option>
                    }
                </select>
            </div>
            <p></p>
            <div class="form-group">
                <input type="submit" value="Save" class="btn button-colors" />
            </div>
        </form>
    </div>
</div>
<p></p>
<div>
    <a asp-action="ManageUsers" class="btn button-colors">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TaskLancer/Views/BackOffice/Index.cshtml
@{
    ViewData["Title"] = "BackOffice - Manage Tags";
}
<h4 class="pt-3">BackOffice - Manage Tags</h4>
<hr />
<div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="BackOffice" asp-action="Index">Manage Content</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="ManageUsers">Manage Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="Statistics">Statistics</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <div>
                @if (User.IsInRole("administrator"))
                    {
                        <a class="nav-link tasklancer-color" asp-controller="SkillTags" asp-action="Index">Manage SkillTags</a>
                        <a class="nav-link tasklancer-color" asp-controller="CategoryTags" asp-action="Index">Manage CategoryTags</a>
                    }
                else
                    {
                        <p>Não tem Acesso a esta página</p>
                    }
            </div>
        </div>
</div>

TaskLancer/Views/BackOffice/ManageUsers.cshtml
@model IEnumerable<TaskLancer.Controllers.BackOfficeController.InputModel>

@{
    ViewData["Title"] = "BackOffice - ManageUsers";
}
<h4 class="pt-3">BackOffice - ManageUsers</h4>
<hr />
<div class="card">
        <div class="card-header">
            <ul class="nav nav-tabs card-header-tabs">
                <li class="nav-item">
                    <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="Index">Manage Content</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" asp-controller="BackOffice" asp-action="ManageUsers">Manage Users</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="Statistics">Statistics</a>
                </li>
            </ul>
        </div>
        <div class="card-body">
            <div>
                @if (User.IsInRole("administrator"))
                    {
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Id)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.UserName)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.UserRole)
                                    </th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                        @foreach (var item in Model) 
                        {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Id)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UserName)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.UserRole)
                                    </td>
                                    <td>
                                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn button-colors">Edit</a>
                                    </td>
                                </tr>
                        }
                            </tbody>
                        </table>
                    }
                else
                    {
                        <p>Não tem Acesso a esta página</p>
                    }
            </div>
        </div>
</div>

TaskLancer/Views/BackOffice/Statistics.cshtml
@{
    ViewData["Title"] = "BackOffice - Statistics";
}

@model TaskLancer.Controllers.BackOfficeController.StatisticsModel

<h4 class="pt-3">BackOffice - Statistics</h4>
<hr />
<div class="card">
    <div class="card-header">
        <ul class="nav nav-tabs card-header-tabs">
            <li class="nav-item">
                <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="Index">Manage Content</a>
            </li>
            <li class="nav-item">
                <a class="nav-link tasklancer-color" asp-controller="BackOffice" asp-action="ManageUsers">Manage Users</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" asp-controller="BackOffice" asp-action="Statistics">Statistics</a>
            </li>
        </ul>
    </div>
    <div class="card-body">
        <div class="row row-cols-1 row-cols-md-2 g-4">
            <div class="col">
                <div class="card h-100">
                      <h5 class="card-header">Users</h5>
                      <div class="card-body">
                            <div class="row row-cols-2">
                                <dt>
                                    <p>Total Users:</p>
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.totalUsers)
                                </dd>
                                <dt>
                                    <p>Total Managers:</p>
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.totalManagers)
                                </dd>
                                <dt>
                                    <p>Total Freelancers:</p>
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.totalFreelancers)
                                </dd>
                            </div>
                      </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <h5 class="card-header">Users Chart</h5>
                    <div class="card-body">
                        <canvas class="my-4" style="max-height: 15em;" id="pie1"></canvas>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                      <h5 class="card-header">Projects/Contracting</h5>
                      <div class="card-body">
                          <div class="row row-cols-2">
                                <dt class="">
                                    <p>Total Projects:</p>
                                </dt>
                                <dd class="">
                                    @Html.DisplayFor(model => model.totalProjects)
                                </dd>
                                <dt class="">
                                    <p>Total Contracting Processes:</p>
                                </dt>
                                <dd class="">
                                    @Html.DisplayFor(model => model.totalContracts)
                                </dd>
                                <dt class="">
                                    <p>Published:</p>
                                </dt>
                                <dd class="">
                                    @Html.DisplayFor(model => model.totalContractsPublished)
                                </dd>
                                <dt class="">
                                    <p>Pending Payment:</p>
                                </dt>
                                <dd class="">
                                    @Html.DisplayFor(model => model.totalContractsPendingPayment)
                                </dd>
                                <dt class="">
                                    <p>Ongoing:</p>
                                </dt>
                                <dd class="">
                                    @Html.DisplayFor(model => model.totalContractsOngoing)
                                </dd>
                                <dt class="">
                                    <p>Under Evaluation:</p>
                                </dt>
                                <dd class="">
                                    @Html.DisplayFor(model => model.totalContractsUnderEvaluation)
                                </dd>
                                <dt class="">
                                    <p>Completed:</p>
                                </dt>
                                <dd class="">
                                    @Html.DisplayFor(model => model.totalContractsCompleted)
                                </dd>
                                <dt class="">
                                    <p>Canceled:</p>
                                </dt>
                                <dd class="">
                                    @Html.DisplayFor(model => model.totalContractsCanceled)
                                </dd>
                                <dt class="">
                                    <p>Average Time Contracts Completed:</p>
                                </dt>
                                <dd class="">
                                    @Html.DisplayFor(model => model.averageTimeContractsCompleted)
                                </dd>
                            </div>
                      </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                    <h5 class="card-header">Contracting Chart</h5>
                    <div class="card-body">
                        <canvas class="my-4" id="bar"></canvas>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card h-100">
                      <h5 class="card-header">Financial</h5>
                      <div class="card-body">
                         <div class="row row-cols-2">
                                <dt>
                                    <p>Total Transactions:</p>
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.totalTransactions)
                                </dd>
                                <dt>
                                    <p>Plataform profit:</p>
                                </dt>
                                <dd>
                                    @Html.DisplayFor(model => model.platformProfit) €
                                </dd>
                         </div>
                      </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.7.1/chart.min.js" integrity="sha512-QSkVNOCYLtj73J4hbmVoOV6KVZuMluZlioC+trLpewV8qMjsWqlIQvkn1KGX2StWvPMdWGBqim1xlC8krl1EKQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
        const ctx1 = document.getElementById('pie1').getContext('2d');
        const myChart1 = new Chart(ctx1, {
            type: 'pie',
            data: {
                labels: ['Managers', 'Freelancers'],
                datasets: [{
                    label: 'Users',
                    data: [@Model.totalManagers, @Model.totalFreelancers],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                    ],
                    borderWidth: 1
                }]
            },
            options: {
            }
        });

        const ctx2 = document.getElementById('bar').getContext('2d');
        const myChart2 = new Chart(ctx2, {
            type: 'bar',
            data: {
                labels: ['Published', 'Pending Payment', 'Ongoing', 'Under Evaluation', 'Completed', 'Canceled'],
                datasets: [{
                    label: 'Contracting State',
                    data: [@Model.totalContractsPublished, @Model.totalContractsPendingPayment,@Model.totalContractsOngoing,@Model.totalContractsUnderEvaluation,@Model.totalContractsCompleted,@Model.totalContractsCanceled],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
</script>