TaskLancer/Controllers/CatalogController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.Web.Http;
using TaskLancer.Data;
using TaskLancer.Models;
using TaskLancer.Models.Catalog.BLL;
using TaskLancer.Models.Contracting.BLL;
using TaskLancer.Models.Contracting.DAL;

namespace TaskLancer.Controllers
{
    public class CatalogController : Controller
    {
        private readonly TaskLancerContext _context;
        private readonly ICatalogService _catalogService;

        public CatalogController(TaskLancerContext context, ICatalogService catalogService)
        {
            _context = context;
            _catalogService = catalogService;
        }

        [Authorize]
        public async Task<IActionResult> Index(InputModel? inputModel)
        {

            //List<ContractingProcess> contractsList = _contractingService.GetAllPublishedContractingProcesses();

            List<SkillTag> allSkillTags = await _context.SkillTag.ToListAsync();

            IEnumerable<SelectListItem> SkillTagsSelectList = new SelectList(allSkillTags, "SkillTagId", "Name");

            ViewBag.SkillTagsSelectList = SkillTagsSelectList;

            var selectedValues = new List<int>();

            if (inputModel.FilterDate == null)
            {
                inputModel.FilterDate = "";
            }

            /*foreach (var contract in contractList)
            {
                contract.SkillTags = allSkillTags;
            }*/

            if (inputModel.SelectedSkillTags != null)
            {
                foreach (var tag in inputModel.SelectedSkillTags)
                {
                    selectedValues.Add(tag);
                }
            }

            List<ContractingProcess> contractsList = _catalogService.GetFilteredContracts(selectedValues, inputModel.FilterDate);

            /*foreach(var skillTag in selectedSkillTags)
            {
                foreach(var contract in contractList)
                {
                    selectedSkillTags.Exists(x => x.SkillTagId == contract.SkillTags);
                }
            }*/

            InputModel input = new InputModel
            {
                PublishedContracts = contractsList,
                FilterDate = inputModel.FilterDate,
                SelectedSkillTags = selectedValues,
            };

            return View(input);
        }



        public class InputModel
        {
            public List<ContractingProcess>? PublishedContracts { get; set; }

            [Display(Name = "Filter Date")]
            public string FilterDate { get; set; }

            [Display(Name = "Skill Tags")]
            public IEnumerable<int>? SelectedSkillTags { get; set; }

        }
    }
}

TaskLancer/Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TaskLancer.Areas.Identity.Data;
using TaskLancer.Data;
using TaskLancer.Models.Contracting.BLL;
using TaskLancer.Models.Contracting.DAL;
using TaskLancer.Models.Project.BLL;
using TaskLancer.Models.Project.DAL;
using TaskLancer.Services;

namespace TaskLancer.Controllers
{
    [Authorize]
    public class DashBoardController : Controller
    {
        private readonly TaskLancerContext _context;
        private readonly UserManager<TaskLancerUser> _userManager;
        private readonly IContractingService _contractingService;
        private readonly IProjectService _projectService;
        private readonly IStatisticsService _statisticsService;

        public DashBoardController(TaskLancerContext context, IStatisticsService statisticsService, UserManager<TaskLancerUser> userManager, IContractingService contractingService, IProjectService projectService)
        {
            _context = context;
            _userManager = userManager;
            _contractingService = contractingService;
            _projectService = projectService;
            _statisticsService = statisticsService;
        }
        
        [Authorize]
        public async Task<IActionResult> UnderConsiderationTasks()
        {
            System.Security.Claims.ClaimsPrincipal currentUser = this.User;

            TaskLancerUser user = await _userManager.GetUserAsync(currentUser);

            List<ContractingProcess> underConsiderationContracts = new List<ContractingProcess>();

            List<ContractingProcess> freelancerContracts = await _contractingService.AllContractingProcessesAsFreelancer(user.Id);

            foreach (var item in freelancerContracts)
            {
                if (item.State == ContractingProcessState.Published)
                {
                    underConsiderationContracts.Add(item);
                }
            }

            return View(underConsiderationContracts.ToList());
        }

        [Authorize]
        public async Task<IActionResult> OnGoingTasks()
        {
            System.Security.Claims.ClaimsPrincipal currentUser = this.User;

            TaskLancerUser user = await _userManager.GetUserAsync(currentUser);

            List<ContractingProcess> ongoingContracts = new List<ContractingProcess>();

            List<ContractingProcess> freelancerContracts = await _contractingService.AllContractingProcessesAsFreelancer(user.Id);

            foreach (var item in freelancerContracts)
            {
                if (item.State == ContractingProcessState.Ordered || item.State == ContractingProcessState.Pending_Payment)
                {
                    ongoingContracts.Add(item);
                }
            }

            return View(ongoingContracts.ToList());
        }

        [Authorize]
        public async Task<IActionResult> CompletedTasks()
        {
            System.Security.Claims.ClaimsPrincipal currentUser = this.User;

            TaskLancerUser user = await _userManager.GetUserAsync(currentUser);

            List<ContractingProcess> completedContracts = new List<ContractingProcess>();

            List<ContractingProcess> freelancerContracts = await _contractingService.AllContractingProcessesAsFreelancer(user.Id);

            foreach (var item in freelancerContracts)
            {
                if (item.State == ContractingProcessState.Completed)
                {
                    completedContracts.Add(item);
                }
            }

            return View(completedContracts.ToList());
        }

        [Authorize]
        public async Task<IActionResult> CanceledTasks()
        {
            System.Security.Claims.ClaimsPrincipal currentUser = this.User;

            TaskLancerUser user = await _userManager.GetUserAsync(currentUser);

            List<ContractingProcess> canceledContracts = new List<ContractingProcess>();

            List<ContractingProcess> freelancerContracts = await _contractingService.AllContractingProcessesAsFreelancer(user.Id);

            foreach (var item in freelancerContracts)
            {
                if (item.State == ContractingProcessState.Canceled)
                {
                    canceledContracts.Add(item);
                }
            }

            return View(canceledContracts.ToList());
        }

        [Authorize]
        public async Task<IActionResult> MyProjects()
        {
            System.Security.Claims.ClaimsPrincipal currentUser = this.User;

            TaskLancerUser user = await _userManager.GetUserAsync(currentUser);
            if(user != null)
            {
                List<Project> userProjects = await _projectService.GetAllUserProjects(user.Id);

                ProjectsList projectList = new ProjectsList
                {
                    projectModels = new List<ProjectModel>()
                };

                foreach (var p in userProjects)
                {
                    projectList.projectModels.Add(new ProjectModel
                    {
                        project = p,
                        totalTasks = await _statisticsService.ProjectTasksTotal(p.ProjectId),
                        totalPaid = await _statisticsService.TotalPaidByProject(p.ProjectId),
                        totalToPay = await _statisticsService.TotalToPayByProject(p.ProjectId),
                    });
                }

                return View(projectList);
            }
            return NotFound();
        }
        public class ProjectsList
        {
            public List<ProjectModel> projectModels { get; set; }
        }

        public class ProjectModel
        {
            public Project project { get; set; }

            public int totalTasks { get; set; }

            public float totalPaid { get; set; }

            public float totalToPay { get; set; }
        }

        [Authorize]
        public async Task<IActionResult> OutsourcedTasks()
        {
            System.Security.Claims.ClaimsPrincipal currentUser = this.User;

            TaskLancerUser user = await _userManager.GetUserAsync(currentUser);

            List<ContractingProcess> managerContracts = await _contractingService.AllContractingProcessesAsManager(user.Id);

            int totalPublished = 0;
            int totalPendingPayment = 0;
            int totalWaitingForDelivery = 0;
            int totalCompleted = 0;
            int totalCanceled = 0;

            foreach(var process in managerContracts)
            {
                if(process.State == ContractingProcessState.Published)
                {
                    totalPublished++;
                }else if(process.State == ContractingProcessState.Pending_Payment)
                {
                    totalPendingPayment++;
                }
                else if (process.State == ContractingProcessState.Ordered)
                {
                    totalWaitingForDelivery++;
                }
                else if (process.State == ContractingProcessState.Completed)
                {
                    totalCompleted++;
                }
                else if (process.State == ContractingProcessState.Canceled)
                {
                    totalCanceled++;
                }
            }

            OutSourcedTasksViewModel model = new OutSourcedTasksViewModel
            {
                contractingProcesses = managerContracts,
                totalPendingPayment = totalPendingPayment,
                totalCompleted = totalCompleted,
                totalCanceled = totalCanceled,
                totalPublished = totalPublished,
                totalWaitingForDelivery = totalWaitingForDelivery              
            };

            return View(model);
        }

        public class OutSourcedTasksViewModel
        {
            public List<ContractingProcess> contractingProcesses { get; set; }

            public int totalPublished { get; set; }

            public int totalPendingPayment { get; set; }

            public int totalWaitingForDelivery { get; set; }

            public int totalCompleted { get; set; }

            public int totalCanceled { get; set; }
        }

        [Authorize]
        public async Task<IActionResult> ManagerStats()
        {
            System.Security.Claims.ClaimsPrincipal currentUser = this.User;

            TaskLancerUser user = await _userManager.GetUserAsync(currentUser);

            ManagerStatisticsModel model = new ManagerStatisticsModel
            {
                totalProjects = await _statisticsService.TotalUserProjects(user.Id),
                totalPrivateProjects = await _statisticsService.UserProjectTotalByPrivacy(user.Id, false),
                totalPublicProjects = await _statisticsService.UserProjectTotalByPrivacy(user.Id, true),
                totalTasks = await _statisticsService.UserCreatedTasksTotal(user.Id),
                totalContracts = await _statisticsService.ContractingProcessesCreatedByManagerTotal(user.Id, null),
                totalContractsPublished = await _statisticsService.ContractingProcessesCreatedByManagerTotal(user.Id, ContractingProcessState.Published),
                totalContractsPendingPayment = await _statisticsService.ContractingProcessesCreatedByManagerTotal(user.Id, ContractingProcessState.Pending_Payment),
                totalContractsWaintingForDelivery = await _statisticsService.ContractingProcessesCreatedByManagerTotal(user.Id, ContractingProcessState.Ordered),
                totalContractsUnderEvaluation = await _statisticsService.ContractingProcessesCreatedByManagerTotal(user.Id, ContractingProcessState.Under_Evaluation),
                totalContractsCompleted = await _statisticsService.ContractingProcessesCreatedByManagerTotal(user.Id, ContractingProcessState.Completed),

TaskLancer/Controllers/ProfileController.cs
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TaskLancer.Areas.Identity.Data;
using TaskLancer.Data;
using TaskLancer.Models;
using TaskLancer.Models.Project;

using TaskLancer.Services;

namespace TaskLancer.Controllers
{
    public class ProfileController : Controller
    {
        private readonly TaskLancerContext _context;
        private readonly UserManager<TaskLancerUser> _userManager;
        private readonly IProfileService _profileService;

        public ProfileController(TaskLancerContext context, UserManager<TaskLancerUser> userManager, IProfileService profileService)
        {
            _context = context;
            _userManager = userManager;
            _profileService = profileService;
        }


        [Authorize]
        public async Task<IActionResult> DetailsUserProfile()
        {
            System.Security.Claims.ClaimsPrincipal currentUser = this.User;
            TaskLancerUser user = await _userManager.GetUserAsync(currentUser);

            if(user != null)
            {
                return RedirectToAction("Details", new { username = user.UserName });
            }

            return NotFound();
        }

        [Authorize]
        // GET: Projects/Details/5
        public async Task<IActionResult> Details(string? username)
        {

            if (username == null)
            {
                return NotFound();
            }

            //var project = await _context.Project
            //    .FirstOrDefaultAsync(m => m.ProjectId == id);

            System.Security.Claims.ClaimsPrincipal currentUser = this.User;

            TaskLancerUser user;

            try{
                user = await _profileService.GetUserWithSkillTagsAsync(username);
            } catch (ArgumentException e)
            {
                Console.WriteLine(e.Message);
                return NotFound();
            }

            ViewBag.hasEdit = User.Identity.Name == user.UserName;

            List<SkillTag> allSkillTags = await _context.SkillTag.ToListAsync();

            IEnumerable<SelectListItem> SkillTagsSelectList = new SelectList(allSkillTags, "SkillTagId", "Name");

            ViewBag.SkillTagsSelectList = SkillTagsSelectList;

            var selectedValues = new List<int>();

            if (user.SkillTags != null)
            {
                foreach (var tag in user.SkillTags)
                {
                    selectedValues.Add(tag.SkillTagId);
                }
            }

            InputModel input = new InputModel
            {
                UserName = user.UserName,
                FullName = user.FirstName + " " + user.LastName,
                Biography = user.Biography,
                Curriculum = user.Curriculum,
                SelectedSkillTags = selectedValues,
                
            };


            return View(input);
        }

        public class InputModel
        {
            public string UserName { get; set; }

            [Display(Name = "Full Name")]
            public string FullName { get; set; }

            [Display(Name = "Biography")]
            public string Biography { get; set; }

            [Display(Name = "Curriculum")]
            public string Curriculum { get; set; }

            [Display(Name = "Skill Tags")]
            public IEnumerable<int> SelectedSkillTags { get; set; }

        }
    }
}

TaskLancer/Views/Shared/CustomError.cshtml
@model ErrorViewModel

<h1 class="text-danger">@ViewData["Title"]</h1>
<h3>@ViewData["Description"]</h3>

@if (Model?.ShowRequestId ?? false)
{
    <p>
        <strong>Request ID:</strong> <code>@Model?.RequestId</code>
    </p>
}

TaskLancer/Views/Shared/_LandingPartial.cshtml
 <div class="col-lg-6 text-white p-4">
        <section class="d-flex flex-column justify-content-center">
            <img src="~/images/TaskLancer_Logo.png" width="100%" class="p-2"/>
            <h3 class="text-center mt-4">What is our mission?</h3>
            <p class="text-center p-2">We intend to develop an open platform that enhances the interconnection between freelancers and small-scale project managers. We seek to encourage transparency of resource allocation and the adoption of adaptable work methodologies in project development.</p>
<p class="text-center p-2">For project managers, our platform will provide project organization tools, a marketplace of professionals with diverse skillsets and an intuitive and secure process for purchasing services. For crowd-funded project initiators, all tasks and interactions will be public, presenting investors with both a development road-map (by sharing planned tasks) and a record of resource allocation (by revealing transactions made with freelancers).</p>
<p class="text-center p-2">For freelancers producing digital content, the platform seeks to facilitate the discovery of small-to-medium scale work, offering autonomy and choice. It allows the organization of current tasks and the generation of a public record of completed tasks. To assist communication with the client, it will be possible to send direct messages and files. It will establish a secure transaction protocol with the platform as an intermediary.</p>
        </section>
    </div>

TaskLancer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

@using Microsoft.AspNetCore.Identity
@using TaskLancer.Areas.Identity.Data
@inject SignInManager<TaskLancerUser> SignInManager
@inject UserManager<TaskLancerUser> UserManager

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskLancer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskLancer.styles.css" asp-append-version="true" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/download.js"></script>
    <link href="~/lib/bootstrap-star-rating/css/star-rating.css" media="all" rel="stylesheet" type="text/css" />
    <script src="~/lib/bootstrap-star-rating/js/star-rating.js"></script>
    <link href="~/lib/bootstrap-star-rating/themes/krajee-svg/theme.css" media="all" rel="stylesheet" type="text/css" />
    <script src="~/lib/bootstrap-star-rating/themes/krajee-svg/theme.js"></script>
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">


    <link rel="manifest" href="/manifest.json">
</head>

<style>
    .navbar {
        background: #008085;
    }


</style>

<body class="d-flex flex-column vh-100">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/TaskLancer_Logo.png" height="50"/></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex">
                    <div class="flex-fill">
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        DashBoard
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li><a class="dropdown-item card-item-style" style="width: 200px;" asp-controller="DashBoard" asp-action="MyProjects">Manager Dashboard</a></li>
                                        <div class="dropdown-divider"></div>
                                        <li><a class="dropdown-item card-item-style" style="width: 200px;" asp-controller="DashBoard" asp-action="UnderConsiderationTasks">Freelancer Dashboard</a></li>         
                                    </ul>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link " asp-area="" asp-controller="Profile" asp-action="DetailsUserProfile">My Profile</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link " asp-area="" asp-controller="UserPayments" asp-action="UnpaidPayments">Payments</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link " asp-area="" asp-controller="Catalog" asp-action="Index">Task Catalog</a>
                                </li>
                                @if (User.IsInRole("administrator"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link " asp-area="" asp-controller="BackOffice" asp-action="Index">BackOffice</a>
                                    </li>
                                }
                            </ul>
                        }
                    </div>  
                    <div>
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="overflow-auto flex-fill d-flex flex-column">
         <main role="main" class="container flex-fill d-flex flex-column">
        @RenderBody()
    </main>
    @Html.Partial("_UserManualPartial");
    <footer class="border-top py-2 mt-2">
        <div class="container d-flex justify-content-between">
            <div class="d-flex">
                &copy; 2022 - TaskLancer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
            
                 <button type="button" class="btn button-colors" onclick='showUserManual("item-1")'>User Manual</button>

        </div>
    </footer>
    </div>
    

    <script type="text/javascript">
        $(document).ready(function(){
            if ('serviceWorker' in navigator) {
                window.addEventListener("load", () => {
                    navigator.serviceWorker.register("/js/ServiceWorker.js")
                        .then((reg) => {
                            if (Notification.permission === "granted") {
                                $("#form").show();                           
                                getSubscription(reg);
                            }else{
                                requestNotificationAccess(reg);
                            }
                        });
                });
            } 
        })
        

        function requestNotificationAccess(reg) {
            Notification.requestPermission(function (status) {              
                if (status == "granted") {                  
                    $("#form").show();
                    getSubscription(reg);
                }
            });
        }

        function getSubscription(reg) {
            reg.pushManager.getSubscription().then(function (sub) {
                if (sub === null) {
                    reg.pushManager.subscribe({
                        userVisibleOnly: true,
                        applicationServerKey: "BDCDSNTJBiu4uICZxH0lfCxBuycfxRPCMV7nOMnHMos7AKC8LAeTEItTBURAah_dqCLpgPXb_ag40o3g5xX2ZoM"
                    }).then(function (sub) {
                        fetch('/NotificationSubscriptions/RegisterWebPushSubscription', {
                            method: "post",
                            headers: {
                                'Content-type': 'application/json'
                            },
                            body: JSON.stringify({
                                endpoint: sub.endpoint,
                                p256dh: arrayBufferToBase64(sub.getKey("p256dh")),
                                auth: arrayBufferToBase64(sub.getKey("auth"))
                            })
                        });
                    }).catch(function (e) {
                        console.error("Unable to subscribe to push", e);
                    });
                } else {
                    console.log(sub.endpoint);
                    console.log(arrayBufferToBase64(sub.getKey("p256dh")));
                    console.log(arrayBufferToBase64(sub.getKey("auth")));
                    console.dir(sub);
                }
            });
        }

        function arrayBufferToBase64(buffer) {
            var binary = '';
            var bytes = new Uint8Array(buffer);
            var len = bytes.byteLength;
            for (var i = 0; i < len; i++) {
                binary += String.fromCharCode(bytes[i]);
            }
            return window.btoa(binary);
        }


    </script>

  
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskLancer/Views/Shared/_LayoutLanding.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TaskLancer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TaskLancer.styles.css" asp-append-version="true" />
    <style>
        body {
            background: #008085;
            background-image: url("/images/background2.png");
            background-size: cover;
        }

        footer {
            background: #fff;
        }
    </style>
</head>
<body>
    <div class="container my-4 p-4">
        <main role="main" class="pb-5">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer">
        <div class="container">
            &copy; 2022 - TaskLancer - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

TaskLancer/Views/Shared/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        @Model
    </div>
}